version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media       # 媒体文件持久化
      - ./staticfiles:/app/staticfiles  # 静态文件
      - ./hanzi_app:/app/hanzi_app  # 代码热更新（开发时使用）
    environment:
      - DJANGO_SETTINGS_MODULE=hanzi_project.settings
      - DB_HOST=db
      - DB_NAME=hanzi_db
      - DB_USER=root
      - DB_PASSWORD=123456
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql  # 数据库持久化
    environment:
      - MYSQL_DATABASE=hanzi_db
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: